repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs[compatible-mypy]
          - djangorestframework-stubs
          - python-decouple
          - django
          - djangorestframework
          - djangorestframework-simplejwt
          - django-htmx
          - django-redis
          - django-cors-headers
          - cloudinary
          - django-cloudinary-storage
          - wagtail
        args: ["--config-file=pyproject.toml"]

  - repo: local
    hooks:
      - id: no-literal-wagtail-tags
        name: Prevent literal Wagtail template tags in HTML output
        entry: python check_templates_no_literal_tags.py
        language: system
        pass_filenames: false
